# Generated by Django 4.2.28 on 2026-02-04 18:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Pelada',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Nome')),
                ('date', models.DateField(verbose_name='Data')),
                ('time', models.TimeField(verbose_name='Horário')),
                ('location', models.CharField(max_length=300, verbose_name='Local')),
                ('status', models.CharField(choices=[('open', 'Aberta'), ('active', 'Em andamento'), ('finished', 'Finalizada')], default='open', max_length=20, verbose_name='Status')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
            ],
            options={
                'verbose_name': 'Pelada',
                'verbose_name_plural': 'Peladas',
                'ordering': ['-date', '-time'],
            },
        ),
        migrations.CreateModel(
            name='PeladaPlayer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('confirmed_at', models.DateTimeField(auto_now_add=True, verbose_name='Confirmado em')),
                ('pelada', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='peladas.pelada', verbose_name='Pelada')),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Jogador')),
            ],
            options={
                'verbose_name': 'Jogador na Pelada',
                'verbose_name_plural': 'Jogadores na Pelada',
                'ordering': ['confirmed_at'],
                'unique_together': {('pelada', 'player')},
            },
        ),
        migrations.AddField(
            model_name='pelada',
            name='confirmed_players',
            field=models.ManyToManyField(related_name='peladas_confirmed', through='peladas.PeladaPlayer', to=settings.AUTH_USER_MODEL, verbose_name='Jogadores confirmados'),
        ),
        migrations.AddField(
            model_name='pelada',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='peladas_created', to=settings.AUTH_USER_MODEL, verbose_name='Criado por'),
        ),
    ]
