# Generated by Django 4.2.28 on 2026-02-05 16:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('players', '0001_initial'),
        ('peladas', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pelada',
            name='confirmed_players',
        ),
        migrations.AddField(
            model_name='pelada',
            name='format',
            field=models.CharField(choices=[('4x4', '4 contra 4'), ('5x5', '5 contra 5')], default='5x5', max_length=10, verbose_name='Formato'),
        ),
        migrations.AddField(
            model_name='pelada',
            name='players',
            field=models.ManyToManyField(blank=True, related_name='peladas', through='peladas.PeladaPlayer', to='players.player', verbose_name='Jogadores confirmados'),
        ),
        migrations.AlterField(
            model_name='peladaplayer',
            name='player',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='players.player', verbose_name='Jogador'),
        ),
    ]
