# Generated by Django 4.2.28 on 2026-02-05 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Nome completo do jogador', max_length=150, verbose_name='Nome')),
                ('nickname', models.CharField(blank=True, default='', help_text='Apelido do jogador (opcional)', max_length=50, verbose_name='Apelido')),
                ('skill_level', models.IntegerField(choices=[(1, 'Ruim'), (2, 'Médio'), (3, 'Bom')], default=2, help_text='Nível de habilidade: 1=Ruim, 2=Médio, 3=Bom', verbose_name='Peso/Habilidade')),
                ('avatar', models.CharField(blank=True, help_text='Iniciais do nome para avatar', max_length=10, verbose_name='Avatar')),
                ('is_active', models.BooleanField(default=True, help_text='Jogadores inativos não aparecem para seleção', verbose_name='Ativo')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
            ],
            options={
                'verbose_name': 'Jogador',
                'verbose_name_plural': 'Jogadores',
                'ordering': ['name'],
            },
        ),
    ]
