# Generated by Django 4.2.28 on 2026-02-04 18:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('peladas', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Match',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('active', 'Em andamento'), ('finished', 'Finalizada')], default='active', max_length=20, verbose_name='Status')),
                ('started_at', models.DateTimeField(auto_now_add=True, verbose_name='Iniciado em')),
                ('finished_at', models.DateTimeField(blank=True, null=True, verbose_name='Finalizado em')),
                ('pelada', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='matches', to='peladas.pelada', verbose_name='Pelada')),
            ],
            options={
                'verbose_name': 'Partida',
                'verbose_name_plural': 'Partidas',
                'ordering': ['-started_at'],
            },
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nome do Time')),
                ('match', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='teams', to='matches.match', verbose_name='Partida')),
            ],
            options={
                'verbose_name': 'Time',
                'verbose_name_plural': 'Times',
            },
        ),
        migrations.CreateModel(
            name='TeamPlayer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Jogador')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='matches.team', verbose_name='Time')),
            ],
            options={
                'verbose_name': 'Jogador no Time',
                'verbose_name_plural': 'Jogadores no Time',
                'unique_together': {('team', 'player')},
            },
        ),
        migrations.AddField(
            model_name='team',
            name='players',
            field=models.ManyToManyField(related_name='teams', through='matches.TeamPlayer', to=settings.AUTH_USER_MODEL, verbose_name='Jogadores'),
        ),
        migrations.CreateModel(
            name='MatchStats',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stat_type', models.CharField(choices=[('goal', 'Gol'), ('assist', 'Assistência')], max_length=20, verbose_name='Tipo')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Registrado em')),
                ('match', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stats', to='matches.match', verbose_name='Partida')),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='match_stats', to=settings.AUTH_USER_MODEL, verbose_name='Jogador')),
            ],
            options={
                'verbose_name': 'Estatística',
                'verbose_name_plural': 'Estatísticas',
                'ordering': ['created_at'],
            },
        ),
    ]
